# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

apiVersion: v1
kind: Service
metadata:
  name: vespa-feed-service
  labels:
    app: vespa
spec:
  selector:
    app: vespa-feed
  ports:
  - name: api
    port: 8080
    targetPort: 8080
